services:
  - type: web
    name: personainsight-hrm301
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SERVE_STATIC
        value: "true"
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_INITIAL_USERNAME
        value: Nikhil
      - key: ADMIN_INITIAL_PASSWORD
        value: "1626"
